version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: event_management
    volumes:
      - mysql_data:/var/lib/mysql

  go-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: event_management_mysql_1
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: event_management

volumes:
  mysql_data:
